sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t schak83/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true schak83/docker-react npm run test

deploy:
    provider: "elasticbeanstalk"
    region: "us-east-1"
    docker: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-565087585555"
    bucket_path: "docker-react"
    on:
        branch: master
        access_key_id: "$AWS_ACCESS_KEY"
        secret_access_key: 
            secure: "$AWS_SECRET_KEY"
