sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t schak83/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true schak83/docker-react npm run test
  
